buy_me_a_coffee: JoeLurmel
  name: Buy Me a Coffee
  url: https://www.buymeacoffee.com/joelurmelf
  description: If you find my tools useful and would like to support my work, consider buying me a coffee! Your support helps me continue developing and maintaining these tools.
